package frc.robot.commands;

import static edu.wpi.first.wpilibj2.command.Commands.*;
import static edu.wpi.first.wpilibj2.command.button.RobotModeTriggers.autonomous;

import choreo.auto.AutoFactory;
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
import choreo.trajectory.SwerveSample;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.doglog.DogLog;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.networktables.BooleanPublisher;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.lib.FaultLogger;
import frc.lib.FaultsTable.FaultType;
import frc.lib.InputStream;
import frc.robot.subsystems.Climb;
import frc.robot.subsystems.Hopper;
import frc.robot.subsystems.Shooter;
import frc.robot.subsystems.Swerve;
import frc.robot.subsystems.intake.IntakeFeed;
import frc.robot.subsystems.intake.IntakePivot;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Consumer;
import java.util.function.Supplier;

/** Generates the modular auto. */
public class ModularAuto {
  private final AutoFactory _factory;
  private final HashMap<String, Command> _bindings = new HashMap<>();

  private Command _routineCmd;

  private final Swerve _swerve;

  private boolean _aimAtTarget = false;

  // file management
  private final String layoutDir = "layouts";
  private final ObjectMapper _jsonReader = new ObjectMapper();

  private final Map<String, Map<String, Object>> _layouts = new HashMap<>();

  // nt
  private final SendableChooser<String> _layoutChooser = new SendableChooser<String>();

  private final BooleanPublisher _isAutoGenerated;
  private final AtomicReference<String> _latestLayout = new AtomicReference<>();

  public ModularAuto(
      Shooter shooter,
      Hopper hopper,
      IntakePivot intakePivot,
      IntakeFeed intakeFeed,
      Climb climb,
      Swerve swerve,
      Supplier<Rotation2d> shotHeadingSupplier,
      Consumer<Runnable> addPeriodic) {
    _swerve = swerve;

    _factory =
        new AutoFactory(
            _swerve::getPose,
            _swerve::resetPose,
            sample -> {
              if (_aimAtTarget) {
                _swerve.followTrajectoryFacing((SwerveSample) sample, shotHeadingSupplier.get());
                return;
              }

              _swerve.followTrajectory((SwerveSample) sample);
            },
            true,
            _swerve,
            (traj, isActive) -> {
              DogLog.log("Auto/Current Trajectory", traj.getPoses());
              DogLog.log("Auto/Current Trajectory Name", traj.name());
              DogLog.log("Auto/Current Trajectory Duration", traj.getTotalTime());
              DogLog.log("Auto/Current Trajectory Is Active", isActive);
            });

    _bindings.put(
        "shoot",
        sequence(runOnce(() -> _aimAtTarget = true), parallel(hopper.feedShot(), shooter.shoot())));

    _bindings.put(
        "shoot still",
        parallel(
                _swerve.driveFacing(InputStream.zero, InputStream.zero, shotHeadingSupplier),
                hopper.feedShot(),
                shooter.shoot())
            .withTimeout(1));

    _bindings.put(
        "stop shooting",
        sequence(runOnce(() -> _aimAtTarget = false), parallel(hopper.feedStop(), shooter.idle())));

    _bindings.put("pivot lower", intakePivot.lower());

    _bindings.put("pivot raise", intakePivot.raise());

    _bindings.put("feed in", intakeFeed.feedIn());

    _bindings.put("feed stop", intakeFeed.feedStop());

    _bindings.put("extend", climb.extend());

    _bindings.put("climb", climb.climb());

    _bindings.forEach((name, command) -> _factory.bind(name, command));

    _isAutoGenerated =
        NetworkTableInstance.getDefault()
            .getTable("Robot/Auto")
            .getBooleanTopic("Is Auto Generated")
            .publish();

    _isAutoGenerated.set(false);

    // fill the choosers
    File dir = new File(Filesystem.getDeployDirectory() + "/" + layoutDir);

    for (File layoutFile : dir.listFiles()) {
      try {
        Map<String, Object> layoutJson =
            _jsonReader.readValue(layoutFile, new TypeReference<Map<String, Object>>() {});

        Object name = layoutJson.get("name");

        _layouts.put(name.toString(), layoutJson);
        _layoutChooser.addOption(name.toString(), name.toString());

      } catch (Exception e) {
        FaultLogger.report(
            "Layout (" + layoutFile.getName() + ") failed to load.", FaultType.ERROR);
      }
    }

    _layoutChooser.setDefaultOption("Default", "Default");
    _layoutChooser.onChange(_latestLayout::set);

    autonomous().onTrue(runOnce(() -> _aimAtTarget = false));

    addPeriodic.accept(
        () -> {
          String latestLayout = _latestLayout.getAndSet(null);

          if (latestLayout != null) {
            generateLayoutAuto(latestLayout);
          }
        });

    SmartDashboard.putData("Auto Chooser", _layoutChooser);

    generateLayoutAuto(_layoutChooser.getSelected());
  }

  /** The auto generated from the specified layout. */
  public Command getAutoScheduler() {
    return deferredProxy(() -> _routineCmd).withName("Modular Auto");
  }

  // generate the modular auto
  private void generateLayoutAuto(String layoutName) {
    _isAutoGenerated.set(false);

    if (!_layouts.containsKey(layoutName)) {
      _routineCmd = idle();
      return;
    }

    AutoRoutine routine = _factory.newRoutine(layoutName);
    AutoTrajectory trajectory = routine.trajectory(layoutName, 0);

    List<Integer> splits = routine.trajectory(layoutName).getRawTrajectory().splits();

    @SuppressWarnings("unchecked")
    Map<String, List<String>> splitCommands =
        (Map<String, List<String>>) _layouts.get(layoutName).get("splitCommands");

    routine.active().onTrue(sequence(trajectory.resetOdometry(), trajectory.cmd()));

    // don't chain next trajectory if there is only 1 trajectory
    if (splits.size() == 1) {
      SequentialCommandGroup splitCommand = new SequentialCommandGroup();

      for (String command : splitCommands.get("0")) {
        splitCommand.addCommands(_bindings.get(command));
      }

      trajectory.done().onTrue(splitCommand);
    }

    for (int i = 0; i < splits.size() - 1; i++) {
      AutoTrajectory nextTrajectory = routine.trajectory(layoutName, i + 1);

      SequentialCommandGroup splitCommand = new SequentialCommandGroup();

      for (String command : splitCommands.get(Integer.toString(i))) {
        splitCommand.addCommands(_bindings.get(command));
      }

      splitCommand.addCommands(nextTrajectory.cmd());

      trajectory.done().onTrue(splitCommand);

      trajectory = nextTrajectory;
    }

    _routineCmd = routine.cmd();

    _isAutoGenerated.set(true);
  }
}
