package frc.robot.commands;

import static edu.wpi.first.wpilibj2.command.Commands.*;
import static edu.wpi.first.wpilibj2.command.button.RobotModeTriggers.autonomous;

import choreo.auto.AutoFactory;
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
import choreo.trajectory.SwerveSample;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.doglog.DogLog;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.networktables.BooleanPublisher;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import frc.lib.FaultLogger;
import frc.lib.FaultsTable.FaultType;
import frc.robot.subsystems.Climb;
import frc.robot.subsystems.Hopper;
import frc.robot.subsystems.Shooter;
import frc.robot.subsystems.Swerve;
import frc.robot.subsystems.intake.IntakeFeed;
import frc.robot.subsystems.intake.IntakePivot;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;

/** Generates the modular auto. */
public class ModularAuto {
  private final AutoFactory _factory;
  private final HashMap<String, Command> _bindings = new HashMap<>();

  private Command _routineCmd;

  private final Swerve _swerve;

  private boolean _aimAtTarget = false;

  // file management
  private final String layoutDir = "layouts";
  private final ObjectMapper _jsonReader = new ObjectMapper();

  private final HashMap<String, Map<String, Object>> _layouts = new HashMap<>();

  // nt
  private final SendableChooser<String> _layoutChooser = new SendableChooser<String>();

  private final BooleanPublisher _isAutoGenerated;

  public ModularAuto(
      Shooter shooter,
      Hopper hopper,
      IntakePivot intakePivot,
      IntakeFeed intakeFeed,
      Climb climb,
      Swerve swerve,
      Supplier<Rotation2d> shotHeadingSupplier) {
    _swerve = swerve;

    _factory =
        new AutoFactory(
            _swerve::getPose,
            _swerve::resetPose,
            sample -> {
              if (_aimAtTarget) {
                _swerve.followTrajectoryFacing((SwerveSample) sample, shotHeadingSupplier.get());
                return;
              }

              _swerve.followTrajectory((SwerveSample) sample);
            },
            true,
            _swerve,
            (traj, isActive) -> {
              DogLog.log("Auto/Current Trajectory", traj.getPoses());
              DogLog.log("Auto/Current Trajectory Name", traj.name());
              DogLog.log("Auto/Current Trajectory Duration", traj.getTotalTime());
              DogLog.log("Auto/Current Trajectory Is Active", isActive);
            });

    _bindings.put(
        "shoot",
        sequence(runOnce(() -> _aimAtTarget = true), parallel(hopper.feedShot(), shooter.shoot())));

    _bindings.put(
        "stop shooting",
        sequence(runOnce(() -> _aimAtTarget = false), parallel(hopper.feedStop(), shooter.idle())));

    _bindings.put("pivot lower", intakePivot.lower());

    _bindings.put("pivot raise", intakePivot.raise());

    _bindings.put("feed in", intakeFeed.feedIn());

    _bindings.put("feed stop", intakeFeed.feedStop());

    _bindings.put("extend", climb.extend());

    _bindings.put("climb", climb.climb());

    _bindings.forEach((name, command) -> _factory.bind(name, command));

    _isAutoGenerated =
        NetworkTableInstance.getDefault()
            .getTable("Robot/Auto")
            .getBooleanTopic("Is Auto Generated")
            .publish();
    _isAutoGenerated.set(false);

    // fill the choosers
    File dir = new File(Filesystem.getDeployDirectory() + "/" + layoutDir);

    for (File layoutFile : dir.listFiles()) {
      try {
        Map<String, Object> layoutJson =
            _jsonReader.readValue(layoutFile, new TypeReference<Map<String, Object>>() {});

        Object name = layoutJson.get("name");

        if (name == null) {
          throw new RuntimeException(); // blank error to trigger catch
        }

        _layouts.put(name.toString(), layoutJson);
        _layoutChooser.addOption(name.toString(), name.toString());

      } catch (Exception e) {
        FaultLogger.report(
            "Layout (" + layoutFile.getName() + ") failed to load.", FaultType.ERROR);
      }
    }

    _layoutChooser.setDefaultOption("Empty", "Empty");

    // add onchange listeners
    _layoutChooser.onChange(
        layout -> {
          generateLayoutAuto(layout);
        });

    // put choosers on nt
    SmartDashboard.putData("Auto Chooser", _layoutChooser);

    autonomous().onTrue(runOnce(() -> _aimAtTarget = false));

    generateLayoutAuto(_layoutChooser.getSelected());
  }

  /** The auto generated from the specified layout. */
  public Command getAutoScheduler() {
    return deferredProxy(() -> _routineCmd).withName("Modular Auto");
  }

  // generate the modular auto
  private void generateLayoutAuto(String layoutName) {
    _isAutoGenerated.set(false);

    AutoRoutine routine = _factory.newRoutine(layoutName);
    AutoTrajectory trajectory = routine.trajectory(layoutName);

    Map<String, Object> layout = _layouts.get(layoutName);

    for (int split : routine.trajectory(layoutName).getRawTrajectory().splits()) {
      // todo
    }

    routine.active().onTrue(sequence(trajectory.resetOdometry(), trajectory.cmd()));

    _routineCmd = routine.cmd();

    _isAutoGenerated.set(true);
  }
}
