package frc.robot.commands;

import static edu.wpi.first.wpilibj2.command.Commands.*;

import choreo.auto.AutoFactory;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.doglog.DogLog;
import edu.wpi.first.networktables.BooleanPublisher;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import frc.lib.FaultLogger;
import frc.lib.FaultsTable.FaultType;
import frc.robot.subsystems.Swerve;
import java.io.File;
import java.util.Map;
import java.util.function.Consumer;

/** Generates the modular auto. */
public class ModularAuto {
  private enum Side {
    Left("L"),
    Center("C"),
    Right("R");

    private final String _prefix;

    private Side(String prefix) {
      _prefix = prefix;
    }

    public String getPrefix() {
      return _prefix;
    }
  }

  private final AutoFactory _factory;

  private Command _routineCmd;

  private final Swerve _swerve;
  // private final Superstructure _superstructure;

  // file management
  private final String layoutDir = "layouts";
  private final ObjectMapper _jsonReader = new ObjectMapper();

  // nt
  private final SendableChooser<String> _layoutChooser = new SendableChooser<String>();
  private final SendableChooser<Side> _sideChooser = new SendableChooser<Side>();

  private final BooleanPublisher _isAutoGenerated;

  public ModularAuto(Swerve swerve, Superstructure superstructure, Consumer<Runnable> addPeriodic) {
    _swerve = swerve;
    // _superstructure = superstructure;

    _factory =
        new AutoFactory(
            _swerve::getPose,
            _swerve::resetPose,
            _swerve::followTrajectory,
            true,
            _swerve,
            (traj, isActive) -> {
              DogLog.log("Auto/Current Trajectory", traj.getPoses());
              DogLog.log("Auto/Current Trajectory Name", traj.name());
              DogLog.log("Auto/Current Trajectory Duration", traj.getTotalTime());
              DogLog.log("Auto/Current Trajectory Is Active", isActive);
            });

    _isAutoGenerated = NetworkTableInstance.getDefault().getTable("Robot/Auto").getBooleanTopic("Is Auto Generated").publish();
    _isAutoGenerated.set(false);

    // fill the choosers
    File dir = new File(Filesystem.getDeployDirectory() + "/" + layoutDir);

    for (File layoutFile : dir.listFiles()) {
      try {
        Map<String, Object> layoutJson = _jsonReader.readValue(layoutFile, new TypeReference<Map<String, Object>>() {});

        Object name = layoutJson.get("name");

        if (name == null) {
          throw new RuntimeException(); // blank error to trigger catch
        }

        _layoutChooser.addOption(name.toString(), name.toString());
      } catch (Exception e) {
        FaultLogger.report("Layout (" + layoutFile.getName() + ") failed to load.", FaultType.ERROR);
      }
    }

    _layoutChooser.setDefaultOption("Empty", "Empty");

    for (Side side : Side.values()) {
      _sideChooser.addOption(side.toString(), side);
    }

    _sideChooser.setDefaultOption(Side.Center.toString(), Side.Center);

    // add onchange listeners
    _layoutChooser.onChange(layout -> {
      generateAuto(layout);
    });

    _sideChooser.onChange(side -> {
      generateAuto(_layoutChooser.getSelected());
    });

    // put choosers on nt
    SmartDashboard.putData(_layoutChooser);
    SmartDashboard.putData(_sideChooser);
  }

  /** The auto generated from the specified layout. */
  public Command getAuto() {
    return _routineCmd.withName("Modular Auto");
  }

  /** The auto generated from the specified layout. */
  public Command getAutoScheduler() {
    return deferredProxy(() -> _routineCmd).withName("Modular Auto");
  }

  // generate the modular auto
  private void generateAuto(String layoutName) {
    _isAutoGenerated.set(false);

    String sidePrefix = _sideChooser.getSelected().getPrefix();
    _routineCmd = _factory.newRoutine(sidePrefix + layoutName).cmd();

    _isAutoGenerated.set(true);
  }
}
